name: tests
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Install sass
        run: |
          curl -LO https://github.com/sass/dart-sass/releases/download/1.45.0/dart-sass-1.45.0-linux-x64.tar.gz
          tar -xzf dart-sass-1.45.0-linux-x64.tar.gz
          echo "$PWD/dart-sass" >> $GITHUB_PATH
      - name: Run tests
        run: make test
